site_name: ppager
repo_url: https://github.com/berk-karaal/ppager
repo_name: berk-karaal/ppager
edit_uri: ""

theme:
  features:
    - content.code.annotate 
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate 
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Home: "index.md"
  - Features: "features.md"
  - "Library Usage":
    - "Basic Structure": "library/basic_structure.md"
    - "Namings": "library/namings.md"
    - "Attributes": "library/attributes.md"
    - "Colors": "library/colors.md"
    - "Return Codes": "library/return_codes.md"

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables